In [2]:
words = open('names.txt', 'r').read().splitlines()

In [ ]:
words[:10]

In [ ]:
b = {}
for w in words:
    chs = ['<S>'] + list(w) + ['<E>']
    
    for ch1, ch2 in zip(chs, chs[1:]):
        # count (ch1, ch2) in b
        if (ch1, ch2) in b:
            b[(ch1, ch2)] += 1
        else:
            b[(ch1, ch2)] = 1
            
sorted(b.items(), key=lambda x: x[1])
            
b

In [24]:
chars = sorted(list(set(''.join(words))))
stoi = {s: i for i, s in enumerate(chars)}
stoi['<S>'] = len(stoi)
stoi['<E>'] = len(stoi)

In [8]:
# import torch

# a = torch.zeros((28,28), dtype=torch.float32)

# for w in words:
    

In [37]:
# broadcash semantics

import torch

x1 = torch.randn((9, 1, 28,28), dtype=torch.float32)
x2 = torch.ones((1, 10, 28,28), dtype=torch.float32)

(x1 + x2).shape

(x1 + x2)

tensor([[[[ 9.4911e-01,  1.4312e+00,  1.7331e+00,  ...,  1.1557e+00,
            1.2160e+00,  1.7798e+00],
          [ 1.2970e+00,  1.7498e+00,  3.6356e-01,  ...,  2.0735e+00,
            1.9934e+00,  8.1368e-01],
          [-3.7125e-01,  2.3433e+00,  2.8187e-01,  ...,  1.5352e+00,
            1.4234e+00,  7.3185e-01],
          ...,
          [ 3.7630e+00,  2.6525e+00,  2.9133e+00,  ...,  1.8863e+00,
            6.5781e-01,  1.3519e+00],
          [ 1.7213e+00,  9.5368e-01,  5.6391e-01,  ...,  1.5350e+00,
           -1.5968e-01, -2.6761e-01],
          [ 1.1671e+00,  1.1743e+00,  6.8588e-02,  ...,  1.5578e+00,
            1.8951e+00,  1.6190e+00]],

         [[ 9.4911e-01,  1.4312e+00,  1.7331e+00,  ...,  1.1557e+00,
            1.2160e+00,  1.7798e+00],
          [ 1.2970e+00,  1.7498e+00,  3.6356e-01,  ...,  2.0735e+00,
            1.9934e+00,  8.1368e-01],
          [-3.7125e-01,  2.3433e+00,  2.8187e-01,  ...,  1.5352e+00,
            1.4234e+00,  7.3185e-01],
          ...,
     

In [48]:
import torch.nn.functional as F
xs = torch.randint(0, 28, (11, ), dtype=torch.int64)
print(xs)
F.one_hot(xs, num_classes=28)

tensor([21, 27, 12, 20,  0, 10, 12, 19, 23, 23, 11])


tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
         0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0